export enum Category {
  FICTION = 'fiction',
  NON_FICTION = 'non_fiction',
  SCIENCE = 'science',
  TECHNOLOGY = 'technology',
  HISTORY = 'history',
  BIOGRAPHY = 'biography',
  ART = 'art',
  CHILDREN = 'children',
  EDUCATION = 'education',
  MYSTERY = 'mystery',
  ROMANCE = 'romance',
  FANTASY = 'fantasy',
  SELF_HELP = 'self_help',
  RELIGION = 'religion',
  POETRY = 'poetry',
  BUSINESS = 'business',
  TRAVEL = 'travel',
  OTHER = 'other',
}
